services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_dapps
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: PronosticoDeportivo
    ports:
      - "5432:5432"
 









  
