name: Test and Tag on Success

on:
  push:
    branches: [ "feature/fix-security" ]
  pull_request:
    branches: [ "feature/fix-security" ]


permissions:
  contents: write

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    
    environment: Workflow
    
    container:
      image: maven:3.9-eclipse-temurin-21

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{secrets.POSTGRES_DB_TEST }}
          POSTGRES_USER: ${{secrets.POSTGRES_USER_TEST }}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD_TEST }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests with Maven
        env:
          POSTGRES_URL: ${{secrets.POSTGRES_URL_TEST }}
          POSTGRES_USER: ${{secrets.POSTGRES_USER_TEST }}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD_TEST }}
          JWT_KEY: ${{secrets.JWT_KEY }}
        run: mvn -B test

      - name: Calculate and Push Next Checkpoint Tag
        if: github.event_name == 'push'  && success()
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          git fetch --tags

          LATEST_TAG=$(git tag --list "checkpoint-*" --sort=v:refname | tail -n 1)

          if [[ -z "$LATEST_TAG" ]]; then
            NEW_TAG="checkpoint-1"
          else
            
            VERSION_NUMBER=$(echo $LATEST_TAG | sed 's/^checkpoint-//')
    
            NEXT_VERSION_NUMBER=$((VERSION_NUMBER + 1))

            NEW_TAG="checkpoint-${NEXT_VERSION_NUMBER}"
          fi

          git tag $NEW_TAG

          git push origin $NEW_TAG
