name: Test and generate Coverage

on:
  push:
    branches: [ "QA" ]
  pull_request:
    branches: [ "QA" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Workflow

    container:
      image: maven:3.9-eclipse-temurin-21

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB_TEST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_TEST }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests and generate JaCoCo report
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL_TEST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_TEST }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        run: mvn clean verify jacoco:report

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Cabezas-Juan-Manuel_unq-dapps-202501-GRUPOM
            -Dsonar.organization=quilmes1978
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
