name: test-app

on:
  push:
    branches: [ "feature/generateTagNameAndVersion" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    environment: Workflow
    
    

 


