name: test-app

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    environment: Workflow

    container:
      image: maven:3.9-eclipse-temurin-21

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests with Maven
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          FD_URL: ${{ secrets.FD_URL }}
          FD_TOKEN: ${{secrets.FD_TOKEN }}
          OP_TOKEN: ${{ secrets.OP_TOKEN }}
          PROFILE: ${{ secrets.PROFILE }}
        run: mvn -B test
        
  trigger-tag-and-deploy-workflow:
    runs-on: ubuntu-latest
    needs: [test]
    permissions: write-all
    environment: Workflow
    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    steps:
      - name: Trigger Tag and Deploy Workflow
        if: github.event_name == 'push' && github.ref_name == 'feature/main'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'tag-and-deploy.yml',
              ref: '${{ github.ref_name }}', 
              inputs: {
                commit_message: context.payload.head_commit.message
              }
            });


  
 


